### ISSUE TITLE
2.1.0-RC版本，获取 access_token 的接口 出错。

### ISSUE THREAD

**Issue by kingze** [mix-php/mix#67]
2.1.0-RC版本
```php
$time = time();
$payload     = [
  "iss" => "http://example.org", // 签发人
  'iat' => $time, // 签发时间
  'exp' => $time + 7200, // 过期时间
  'uid' => $uid
 ];
$auth        = context()->get('auth');
$access_token= $auth->createToken($payload);
```
出现以下错误，这是什么原因造成的呢？如果解决？
```
> Too few arguments to function Mix\Auth\JWT::__construct(), 0 passed in ***//vendor/mix/bean/src/BeanDefinition.php on line 156 and exactly 1 expected
> [code] 0 [type] ArgumentCountError
> [file] ***/vendor/mix/auth/src/JWT.php [line] 53
> [trace] #0 ***/vendor/mix/bean/src/BeanDefinition.php(156): Mix\Auth\JWT->__construct()
> #1 ***/vendor/mix/bean/src/BeanFactoryTrait.php(79): Mix\Bean\BeanDefinition->newInstance(Array)
> #2 ***/vendor/mix/bean/src/BeanInjector.php(41): Mix\Bean\ApplicationContext->getBean('Mix\\Auth\\JWT')
> #3 ***/vendor/mix/bean/src/BeanDefinition.php(149): Mix\Bean\BeanInjector::build(Object(Mix\Bean\ApplicationContext), Array)
> #4 ***/vendor/mix/bean/src/BeanFactoryTrait.php(74): Mix\Bean\BeanDefinition->newInstance(Array)
> #5 ***/vendor/mix/bean/src/ApplicationContext.php(36): Mix\Bean\ApplicationContext-getBean('auth')
> #6***/app/src/Http/Controllers/LoginController.php(47): Mix\Bean\ApplicationContext->get('auth')
> #7 [internal function]: App\Http\Controllers\LoginController->passwd(Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
> #8 ***/app/src/Http/Commands/StartCommand.php(130): call_user_func(Array, Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
> #9 ***/app/src/Http/Commands/StartCommand.php(91): App\Http\Commands\StartCommand->handle(Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
> #10 [internal function]: App\Http\Commands\StartCommand->App\Http\Commands\{closure}(Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
> #11 ***/vendor/mix/http-server/src/HttpServer.php(95): call_user_func(Object(Closure), Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
> #12 [internal function]: Mix\Http\Server\HttpServer->Mix\Http\Server\{closure}(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
> #13 {main}
```

看了一下BeanDefinition.php文件156行代码
```php
$object or $object = new $class();  
```

JWT.php文件的代码是
```php
public function __construct(array $config)
```

**Comment by onanying** [comment]
这个已经修复了在 2.1.0-rc2 版本，你把这个库修改一下版本 composer update一下

**Comment by kingze** [comment]
用全功能安装RC2版本后，出现以下提示:

```[warning] 2019-11-08 16:40:07.595 <10957> openssl_sign(): supplied key param cannot be coerced into a private key
[code] 2 [type] Mix\Console\Exception\ErrorException
[file] ***/vendor/firebase/php-jwt/src/JWT.php [line] 199
[trace] #0 [internal function]: Mix\Console\Error->appError(2, 'openssl_sign():...', '/kdata/wwwroot/...', 199, Array)
#1  ***/vendor/firebase/php-jwt/src/JWT.php(199): openssl_sign('eyJ0eXAiOiJKV1Q...', '', '', 'SHA256')
#2  ***/vendor/firebase/php-jwt/src/JWT.php(170): Firebase\JWT\JWT::sign('eyJ0eXAiOiJKV1Q...', '', 'RS256')
#3  ***/vendor/mix/auth/src/JWT.php(97): Firebase\JWT\JWT::encode(Array, '', 'RS256')
#4  ***/vendor/mix/auth/src/Authorization.php(49): Mix\Auth\JWT->create(Array)
#5  ***/app/src/Http/Controllers/IndexController.php(36): Mix\Auth\Authorization->createToken(Array)
#6 [internal function]: App\Http\Controllers\IndexController->index(Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
#7  ***/app/src/Http/Commands/StartCommand.php(129): call_user_func(Array, Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
#8  ***/app/src/Http/Commands/StartCommand.php(90): App\Http\Commands\StartCommand->handle(Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
#9 [internal function]: App\Http\Commands\StartCommand->App\Http\Commands\{closure}(Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
#10 ***/vendor/mix/http-server/src/HttpServer.php(102): call_user_func(Object(Closure), Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
#11 [internal function]: Mix\Http\Server\HttpServer->Mix\Http\Server\{closure}(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#12 {main}
```
是不是需要哪里设置。我把`manifest.php`文件中的`key`改了也没有用
```php
// JWT
        [
            // 类路径
            'class'      => \Mix\Auth\JWT::class,
            // 属性注入
            'properties' => [
                // 钥匙
                'key'       => 'example_key',  //这里改了也没有用
                // 签名算法
                'algorithm' => \Mix\Auth\JWT::ALGORITHM_RS256,
            ],
        ],
```
新手，还请谅解。

**Comment by onanying** [comment]
这个是我搞错了，骨架代码配置应该是下面：

- HS 才是只要一个key

```
        // JWT
        [
            // 类路径
            'class'      => \Mix\Auth\JWT::class,
            // 属性注入
            'properties' => [
                // 钥匙
                'key'       => 'example_key',
                // 签名算法
                'algorithm' => \Mix\Auth\JWT::ALGORITHM_HS256,
            ],
        ],
```

**Comment by kingze** [comment]
可以了，非常感谢。～
