### ISSUE TITLE
APP_DEBUG设为false依然会输出错误信息

### ISSUE THREAD

**Issue by peinhu** [mix-php/mix#74]
```php
Server         Name:      mix-httpd
System         Name:      linux
PHP            Version:   7.2.17
Swoole         Version:   4.4.16
Framework      Version:   2.1.9
Listen         Addr:      0.0.0.0
Listen         Port:      7777
```
需求：APP_DEBUG设为false时不显示错误，或不显示错误详情
实际：APP_DEBUG设为false依然会输出错误，相关数据库字段和框架信息遭到泄露
```php
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '11' for key 'bands_mac_unique'
PDOException code 23000
/vagrant/mixtest/vendor/mix/database/src/AbstractConnection.php line 345

#0 /vagrant/mixtest/vendor/mix/database/src/AbstractConnection.php(345): PDOStatement->execute()
#1 [internal function]: Mix\Database\AbstractConnection->execute()
#2 /vagrant/mixtest/vendor/mix/database/src/Persistent/Connection.php(92): call_user_func_array('parent::execute', Array)
#3 /vagrant/mixtest/vendor/mix/database/src/Connection.php(30): Mix\Database\Persistent\Connection->call('execute', Array)
#4 /vagrant/mixtest/vendor/mix/database/src/Persistent/Connection.php(69): Mix\Database\Connection->call('execute')
#5 /vagrant/mixtest/app/Http/Models/BandModel.php(44): Mix\Database\Persistent\Connection->execute()
#6 /vagrant/mixtest/app/Http/Controllers/BandController.php(66): App\Http\Models\BandModel->add(Object(App\Http\Forms\BandForm))
#7 [internal function]: App\Http\Controllers\BandController->register(Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
#8 /vagrant/mixtest/app/Http/Commands/StartCommand.php(123): call_user_func(Array, Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
#9 /vagrant/mixtest/app/Http/Commands/StartCommand.php(84): App\Http\Commands\StartCommand->handle(Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
#10 [internal function]: App\Http\Commands\StartCommand->App\Http\Commands\{closure}(Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
#11 /vagrant/mixtest/vendor/mix/http-server/src/Server.php(107): call_user_func(Object(Closure), Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
#12 [internal function]: Mix\Http\Server\Server->Mix\Http\Server\{closure}(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#13 {main}

MixPHP V2.1 —— Single-threaded coroutine PHP framework
```
看了下好像debug参数只在日志里用到了，是不是框架无法屏蔽错误，只能自己try...catch处理？

**Comment by onanying** [comment]
@peinhu 这个和其他框架不一样，appdebug  只是控制命令行异常不会打印 trace 信息，而你说的网页、api的遇到异常的输出，需要在这里自行修改 https://www.kancloud.cn/onanying/mixphp2-1/1255279

**Comment by peinhu** [comment]
好的谢谢，后续版本建议加入屏蔽网页、api输出任何异常的功能，或者类似生产模式一样的配置。

**Comment by onanying** [comment]
不会增加这种，因为每个用户需求不一，这个就是要让用户自己去弄，mix 就是这样的设计理念，每个地方都能改成自己要的样子，是个“手动挡车”

**Comment by peinhu** [comment]
明白。
